// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgkqabfbonmcqcpehkfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxna3FhYmZib25tY3FjcGVoa2ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NTQ0NDcsImV4cCI6MjA2OTUzMDQ0N30.G4IndtfbKZ8Ram_XKeMKZc4lcwVJNlguyj2lkUEY6rk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});